### ISSUE TITLE
Move Container<JointAndShapes_t> from hpp::manipulation::Device

### ISSUE THREAD

**Issue by florent-lamiraux** [humanoid-path-planner/hpp-pinocchio#119]
I consider moving member
  `Container <JointAndShapes_t> jointAndShapes;`
from class `hpp::manipulation::Device` to `hpp::pinocchio::Device`. The goal is to ease the construction of `explicit_::ConvexShapeContact` class with a list of names of floor contact surfaces and a list of object contact surfaces.

This implies to move
- `Shape_t`, `JointAndShape_t` and `JointAndShapes_t` definitions to hpp-pinocchio,
- Container template class from hpp-core to hpp-pinocchio.

Does anyone have an objection ?

**Comment by jmirabel** [comment]
This also implies that the environment contact must be in the device. I think we don't want this. For the robot shapes, I agree with moving them to hpp-pinocchio.

If it is only for building the object, there is no need to modify the class itself. You can only add a function. I think it is better to keep the class independent when possible.

**Comment by florent-lamiraux** [comment]
But since we have used pinocchio, have environment contact surfaces not been attached to the joint "universe" ?

**Comment by florent-lamiraux** [comment]
I can maybe find a solution without changing classes, simply by moving simple type definitions to hpp-pinocchio.

**Comment by jmirabel** [comment]
Since the environment is not in the robot, I don't see why the environment surfaces would be in the robot...

**Comment by florent-lamiraux** [comment]
Looking into the code, it seems that ProblemSolver::jointAndShapes is not used: I couldn't find a line in core/problem-solver.cc nor in manipulation/problem-solver.cc that adds data to this member, whereas in hpp-manipulation-urdf/src/srdf/factories/contact.cc, all surfaces are added to the robot.

**Comment by jmirabel** [comment]
Have a look at robot::loadEnvironmentModel in hpp-manipulation-corba.

**Comment by florent-lamiraux** [comment]
I see. Environment contact surfaces are stored in object and copied in ProblemSolver.
