### ISSUE TITLE
loadModel: hardcoded "urdf" & "srdf" paths

### ISSUE THREAD

**Issue by nim65s** [humanoid-path-planner/hpp-pinocchio#134]
Hi,

Some robots in https://github.com/gepetto/example-robot-data have their urdf data in a `robots` directory instead of a `urdf` one.

According to https://gitlab.laas.fr/stack-of-tasks/talos-data/-/issues/2#note_9710, this should not be a big issue, as "HPP can now read any directory". But if I look at https://github.com/humanoid-path-planner/hpp-pinocchio/blob/8d9e202f0d004928bbdee290475d23ba61123376/src/urdf/util.cc#L299 I can still see some hardcoded `"urdf"` around.

Shouldn't we add a `urdfSubdir="urdf"` argument to those functions ?

**Comment by jmirabel** [comment]
You can call `loadModel` directly.

**Comment by nim65s** [comment]
Ok, thanks :)
