### ISSUE TITLE
Joint bounds

### ISSUE THREAD

**Issue by jmirabel** [humanoid-path-planner/hpp-pinocchio#15]
What is the rationale behind tagging methods of `Joint` related to bounds as deprecated ?

**Comment by nmansard** [comment]
I am afraid there is none.

**Comment by jmirabel** [comment]
See https://github.com/humanoid-path-planner/hpp-pinocchio/commit/6e2a520414775327d3ec9474f114ef030a12fbe7

**Comment by nmansard** [comment]
Can you merge
