### ISSUE TITLE
Usage of deprecated flag on OSX

### ISSUE THREAD

**Issue by ymontmarin** [humanoid-path-planner/hpp-pinocchio#197]
Hello,

Since the 5.0.0, it looks like there is some problem with the usage of deprecated flag on clang 15 or 16 on OSX:
```
/Users/runner/miniforge3/conda-bld/hpp-pinocchio_1712346568255/work/include/hpp/pinocchio/device-sync.hh:154:49: error: 'deprecated' attribute cannot be applied to types
  void controlComputation(const Computation_t&) HPP_PINOCCHIO_DEPRECATED {}
```

It prevents the deployment of v5.0.0 hpp stack on conda: https://github.com/conda-forge/hpp-pinocchio-feedstock/pull/24

I remember some old similar problems with the deprecated flag.

Do you have any idea of how to fix this ?

**Comment by florent-lamiraux** [comment]
Hello @ymontmarin 
It seems that since C++14, the keyword "deprecated" should be put at the beginning of the line:
https://en.cppreference.com/w/cpp/language/attributes/deprecated
I did a pull request to fix the issue: https://github.com/humanoid-path-planner/hpp-pinocchio/pull/198.
