### ISSUE TITLE
Geometry placement

### ISSUE THREAD

**Issue by jmirabel** [humanoid-path-planner/hpp-pinocchio#20]
As mentioned earlier, hpp-model computes the geometry placement twice.

I added a computation flag to trigger geometry placement update in `Device::computeForwardKinematics` in hpp-pinocchio. This is not in the hpp-model API. I do not know whether is useful to have `JOINT_POSITION` and `GEOMETRY` flags. I do not see any (motion planning) application where `JOINT_POSITION` would be used without `GEOMETRY`.

Any opinion on this topic ?

**Comment by nmansard** [comment]
Body placements are computed by collision/distance algorithms in Pinocchio, while joint placements are computed (also in Pinocchio) by FK algorithm. 
I suggest to keep it similarly in hpp-pinocchio: update JOINT_POSITION in Device::computeForwardKinematics, and update GEOMETY implicitly when computing collision/distance.
