### ISSUE TITLE
JointPtr_t

### ISSUE THREAD

**Issue by jmirabel** [humanoid-path-planner/hpp-pinocchio#21]
typedef `JointPtr_t` changed from `Joint*` to `boost::shared_ptr<Joint>`.

Among other errors it introduces, every `Joint = NULL` has to be changed because there is no  `boost::shared_ptr<Joint>` constructor taking a integer as argument...

This is rather automatic and generates compilation error so we cannot miss them. But it is annoying we have to change them.

**Comment by nmansard** [comment]
We can add a deprecated operator=(int) in JointPtr_t.

**Comment by nmansard** [comment]
Let's accept to have this compilation error and not add any deprecated (temporary) operator in hpp-pinocchio.
