### ISSUE TITLE
Current forward declaration

### ISSUE THREAD

**Issue by jmirabel** [humanoid-path-planner/hpp-pinocchio#24]
This is a list of the current forward declared types. Any opinion on any of them ?

- [x] `HPP_PREDEF_CLASS (Body);`
- [x] `HPP_PREDEF_CLASS (CollisionObject);`
- [x] `HPP_PREDEF_CLASS (Device);`
- [ ] `//DEPREC HPP_PREDEF_CLASS (DistanceResult);`
- [x] `HPP_PREDEF_CLASS (HumanoidRobot);`
- [x] `HPP_PREDEF_CLASS (Joint);`
- [x] `HPP_PREDEF_CLASS (JointConfiguration);`
- [x] `HPP_PREDEF_CLASS (Gripper);`
- [x] `HPP_PREDEF_CLASS (CenterOfMassComputation);`
- [ ] `enum Request_t {COLLISION, DISTANCE};`
- [x] `typedef double value_type;`
- [x] `typedef Eigen::Matrix <value_type, Eigen::Dynamic, 1> vector_t;`
- [x] `typedef vector_t Configuration_t;`
- [x] `typedef Eigen::Ref <const Configuration_t> ConfigurationIn_t;`
- [x] `typedef Eigen::Ref <Configuration_t> ConfigurationOut_t;`
- [x] `typedef boost::shared_ptr <Configuration_t> ConfigurationPtr_t;`
- [x] `typedef Eigen::Ref <const vector_t> vectorIn_t;`
- [x] `typedef Eigen::Ref <vector_t> vectorOut_t;`
- [x] `typedef Eigen::Matrix<value_type, Eigen::Dynamic, Eigen::Dynamic> matrix_t;`
- [x] `typedef Eigen::Ref <matrix_t> matrixOut_t;`
- [x] `typedef matrix_t::Index size_type;`
- [x] `typedef Eigen::Matrix<value_type, 3, 3> matrix3_t;`
- [x] `typedef Eigen::Matrix<value_type, 3, 1> vector3_t;`
- [x] `typedef  Eigen::Matrix<value_type, 6, Eigen::Dynamic> JointJacobian_t;`
- [x] `typedef  Eigen::Matrix<value_type, 3, Eigen::Dynamic> ComJacobian_t;`
- [x] `typedef Eigen::Block <JointJacobian_t, 3, Eigen::Dynamic> HalfJointJacobian_t;`
- [x] `struct JointVector;`
- [x] `typedef JointVector JointVector_t;`
- [x] `struct ObjectVector;`
- [x] `typedef ObjectVector ObjectVector_t;`
- [x] `typedef boost::shared_ptr<Body> BodyPtr_t;`
- [x] `typedef boost::shared_ptr<const Body> BodyConstPtr_t;`
- [ ] `//typedef std::vector<BodyPtr_t> BodyVector_t;`
- [ ] `typedef fcl::CollisionObject * fclCollisionObjectPtr_t;`
- [ ] `typedef const fcl::CollisionObject * fclConstCollisionObjectPtr_t;`
- [ ] `typedef boost::shared_ptr<CollisionObject> CollisionObjectPtr_t;`
- [ ] `typedef boost::shared_ptr<const CollisionObject> CollisionObjectConstPtr_t;`
- [ ] `//DEPREC typedef std::list <CollisionObjectPtr_t> ObjectVector_t;`
- [x] `typedef boost::shared_ptr <Device> DevicePtr_t;`
- [x] `typedef boost::shared_ptr <const Device> DeviceConstPtr_t;`
- [x] `typedef std::vector <se3::DistanceResult> DistanceResults_t;`
- [x] `typedef boost::shared_ptr <HumanoidRobot> HumanoidRobotPtr_t;`
- [x] `typedef boost::shared_ptr <CenterOfMassComputation> CenterOfMassComputationPtr_t;`
- [x] `typedef boost::shared_ptr<Joint> JointPtr_t;`
- [x] `typedef boost::shared_ptr<const Joint> JointConstPtr_t;`
- [x] `typedef boost::shared_ptr <Gripper> GripperPtr_t;`
- [x] `typedef std::vector <GripperPtr_t> Grippers_t;`
- [ ] `//DEPREC typedef fcl::Transform3f Transform3f;`
- [x] `typedef se3::SE3 Transform3f;`
- [x] `typedef boost::shared_ptr<se3::Model>               ModelPtr_t;`
- [x] `typedef boost::shared_ptr<const se3::Model>         ModelConstPtr_t;`
- [X] `typedef boost::shared_ptr<se3::Data>                DataPtr_t;`
- [X] `typedef boost::shared_ptr<const se3::Data>          DataConstPtr_t;`
- [X] `typedef boost::shared_ptr<se3::GeometryModel>       GeomModelPtr_t;`
- [X] `typedef boost::shared_ptr<const se3::GeometryModel> GeomModelConstPtr_t;`
- [X] `typedef boost::shared_ptr<se3::GeometryData>        GeomDataPtr_t;`
- [X] `typedef boost::shared_ptr<const se3::GeometryData>  GeomDataConstPtr_t;`

**Comment by jmirabel** [comment]
`JointJacobian_t` and `ComJacobian_t`: I do not really like them not being dependant on `value_type` like the rest. But I guess we have no choice yet. Correct ?

**Comment by nmansard** [comment]
We can have a fake dependency, which would be valid as far as value_type is double. 
Pinocchio can not be float (yet).

**Comment by nmansard** [comment]
I do not like to have explicit include in forward (on pinocchio/model, in particular). I think it would be a good idea to have the Jacobian being defined from Eigen directly, possibly with value_type.

**Comment by jmirabel** [comment]
So this would be better:
```cpp
typedef Eigen::Matrix<value_type, 6, Eigen::Dynamic> Jacobian_t;
typedef Eigen::Matrix<value_type, 3, Eigen::Dynamic> ComJacobian_t;
```

**Comment by nmansard** [comment]
I like it. Maybe we could add a static assert in the corresponding 
methods, to check that both types are compatible?

**Comment by jmirabel** [comment]
See a5474bb4c7efba9e1ad67c5600d37a75cd6ad6e3

**Comment by jmirabel** [comment]
Is there something in Eigen to check the "compatibility" for us ?

**Comment by jcarpent** [comment]
As far as I, know there is no such predefined macro. You must define your own and us boost::is_same feature.

**Comment by nmansard** [comment]
There are static asserts in Eigen to check the size of two matrices and whether these sizes are compatible. As proposed by @jcarpent you can also check whether the scalar types are the same. This might only be a warning.
