### ISSUE TITLE
Const and non-const types

### ISSUE THREAD

**Issue by anna-seppala** [humanoid-path-planner/hpp-pinocchio#31]
There are some classes with getters that return ConstPtr_t types (Body->innerObjects() for example), which forces a lot of the pointers within HPP to be changed from Ptr_t to ConstPtr_t. This raises problems when a non-const pointer is needed to create new objects. Is there a way around this problem, maybe some nice and clean way of casting the const pointers to non-const pointers?

**Comment by nmansard** [comment]
Here is a very good answer to your question:
http://stackoverflow.com/questions/1913238/const-shared-ptr-to-shared-ptr

I like the statement: "[it] will do what you're asking for, but [...] you probably shouldn't use it." :)

When writing hpp::pinocchio, we tried to keep the same API, even when design choice were not perfect. Changing a return type from PTR to CONST_PTR is maybe smart, but does not respect this strategy. I think we should modify hpp::pinocchio to more consistently stick to the previous hpp::model API. 

Possibly, when doing this, you might want to post an issue on this page to memorize that a part of the API is badly designed and that it would be could to change it in the future (future meaning when merging pinocchio in hpp is over).
