### ISSUE TITLE
tconfiguration: boost check error

### ISSUE THREAD

**Issue by nmansard** [humanoid-path-planner/hpp-pinocchio#32]
There is a reported bug in Pinocchio (stack-of-tasks/pinocchio#278) in the joint difference and interpolation.
Consequently, the corresponding configuration functions of hpp:;pinocchio are also bugged. A direct consequence is that the test tconfiguration is compiling but not running anymore.

We expect the bug to be fixed in the current week. Currently, the numerical value are close to be correct, so it should be possible to implement functional tests in e.g. hpp::core.

**Comment by jmirabel** [comment]
@jcarpent Could you confirm the bug is solved in Pinocchio now ?

**Comment by jcarpent** [comment]
Yes, indeed. See stack-of-tasks/pinocchio/issues/278 for further details.

**Comment by jmirabel** [comment]
Thanks
